base_url = "https://tojahech.com"
title = "tojahech"
compile_sass = false
build_search_index = false
minify_html = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
